version: 2.1
orbs:
  architect: giantswarm/architect@6.0.0

workflows:
  package-and-push-chart-on-tag:
    jobs:
    - architect/push-to-app-catalog:
        context: architect
        executor: app-build-suite
        name: package-and-push-chart
        app_catalog: control-plane-catalog
        app_catalog_test: control-plane-test-catalog
        chart: alertmanager-to-github
    - architect/push-to-app-collection:
        context: architect
        name: alertmanager-to-github-app-collection
        app_name: alertmanager-to-github
        app_namespace: "alertmanager-to-github"
        app_collection_repo: "alertmanager-to-github-app-collection"
        requires:
          - package-and-push-chart
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v.*/
