version: 2.1
orbs:
  architect: giantswarm/architect@6.7.0

workflows:
  package-and-push-chart-on-tag:
    jobs:
    - architect/push-to-app-catalog:
        context: architect
        executor: app-build-suite
        name: push-to-app-catalog
        app_catalog: giantswarm-catalog
        app_catalog_test: giantswarm-test-catalog
        chart: alertmanager-to-github
