version: 2.1
orbs:
  architect: giantswarm/architect@6.4.0

workflows:
  package-and-push-chart-on-tag:
    jobs:
    - architect/push-to-app-catalog:
        context: architect
        executor: app-build-suite
        name: push-to-app-catalog
        app_catalog: control-plane-catalog
        app_catalog_test: control-plane-test-catalog
        chart: alertmanager-to-github

    - architect/push-to-app-collection:
        context: architect
        name: capa-app-collection
        app_name: alertmanager-to-github
        app_namespace: monitoring
        app_collection_repo: capa-app-collection
        requires:
        - push-to-app-catalog
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v.*/

    - architect/push-to-app-collection:
        context: architect
        name: capz-app-collection
        app_name: alertmanager-to-github
        app_namespace: monitoring
        app_collection_repo: capz-app-collection
        requires:
        - push-to-app-catalog
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v.*/

    - architect/push-to-app-collection:
        context: architect
        name: cloud-director-app-collection
        app_name: alertmanager-to-github
        app_namespace: monitoring
        app_collection_repo: cloud-director-app-collection
        requires:
        - push-to-app-catalog
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v.*/

    - architect/push-to-app-collection:
        context: architect
        name: vsphere-app-collection
        app_name: alertmanager-to-github
        app_namespace: monitoring
        app_collection_repo: vsphere-app-collection
        requires:
        - push-to-app-catalog
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v.*/

    - architect/push-to-app-collection:
        context: architect
        name: proxmox-app-collection
        app_name: alertmanager-to-github
        app_namespace: monitoring
        app_collection_repo: proxmox-app-collection
        requires:
        - push-to-app-catalog
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v.*/