{{- if and .Values.env.ATG_GITHUB_APP_ID .Values.env.ATG_GITHUB_APP_INSTALLATION_ID .Values.env.ATG_GITHUB_APP_PRIVATE_KEY -}}
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  labels: 
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "name" . }}
  namespace: {{ include "namespace" . }}
spec:
  endpointSelector:
    matchLabels:
      {{- include "labels.selector" . | nindent 6 }}
  egress:
    - toEntities:
      - world # Allow access to cloud
  ingress:
    - fromEntities:
        - cluster
{{- end -}}