{{- if .Values.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "name" . }}
  namespace: {{ include "namespace" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  endpoints:
  - interval: 60s
    path: /metrics
    port: http
    scrapeTimeout: 45s
  selector:
    matchLabels:
      {{- include "labels.selector" . | nindent 6 }}
{{- end -}}
